/**
 * Created by Administrator on 2017/02/27 0027.
 */

//登录
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


//首页
export const GET_GOOD_COLLECTIONLIST_SUCCESS = 'GET_GOOD_COLLECTIONLIST_SUCCESS';
export const GET_GOODLIST_SUCCESS = 'GET_GOODLIST_SUCCESS';
export const ClEAN_FORM_DATA = 'ClEAN_FORM_DATA';
export const CHANGE_STARTTIME = 'CHANGE_STARTTIME';
export const CHANGE_PIC = 'CHANGE_PIC';
export const CHANGE_LOGO_PIC = 'CHANGE_LOGO_PIC';
export const CHANGE_TABS = 'CHANGE_TABS';
export const SET_FOLDERID = 'SET_FOLDERID';
export const GET_FUUNDER_SUCCESS = 'GET_FUUNDER_SUCCESS';
export const CHANGE_EDIT_STATU = 'CHANGE_EDIT_STATU';



//public
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';
export const START_CREATE = 'START_CREATE';